import { asWorldRegionId } from '../../types/ids'
import type { CommissionTemplate } from '../../types/commission'

const village = asWorldRegionId('xiaoyu-village')

export const commissionTemplates: readonly CommissionTemplate[] = [
  { id: 'commission:fish-stall-audit', title: '鱼摊验货', description: '带着客栈的账牌去鱼摊核对今日鱼干，顺便问问谁把账算成了武功秘籍。', tier: 'ordinary', regionId: village, target: { kind: 'investigate', id: 'fish-stall', label: '核对鱼摊账牌', contextTags: ['location:fish-stall', 'npc:fishmonger'] }, reward: { wealth: 24, fame: 1, grantKey: 'commission:reward:fish-stall-audit' } },
  { id: 'commission:cat-carrier', title: '猫咪押运', description: '把大黄猫送回客栈，途中不能让它把委托牌当成磨爪板。', tier: 'ordinary', regionId: village, target: { kind: 'deliver', id: 'dahuang-cat', label: '护送大黄猫回客栈', contextTags: ['npc:dahuang-cat', 'quest:find-cat'] }, reward: { wealth: 28, fame: 1, grantKey: 'commission:reward:cat-carrier' } },
  { id: 'commission:herb-pantry', title: '后厨采药', description: '为客栈后厨采回一篮不苦得太过分的药草。', tier: 'ordinary', regionId: village, target: { kind: 'collect', id: 'material:herb', label: '采集后厨药草', count: 3, contextTags: ['resource:herb', 'location:hill-path'] }, reward: { wealth: 30, fame: 1, grantKey: 'commission:reward:herb-pantry' } },
  { id: 'commission:bandit-noise', title: '山口劝架', description: '去山口让吵架的两个小贼知道，菜刀也能当裁判锤。', tier: 'ordinary', regionId: village, target: { kind: 'help', id: 'bandit-duo', label: '调解山口争吵', contextTags: ['enemy:bandit', 'event:argument'] }, reward: { wealth: 34, fame: 2, grantKey: 'commission:reward:bandit-noise' } },
  { id: 'commission:bai-training', title: '白大侠复盘', description: '陪白大侠复盘一场比武，重点记录他为什么总在最后一句话时摆姿势。', tier: 'elite', regionId: village, target: { kind: 'defeat', id: 'bai-daxia', label: '完成白大侠复盘比武', enemyId: 'bai-daxia', contextTags: ['npc:bai-daxia', 'battle:training'] }, reward: { wealth: 72, fame: 4, grantKey: 'commission:reward:bai-training' } },
  { id: 'commission:cleaver-polish', title: '菜刀保养', description: '将一把旧菜刀送到铁匠处保养，不能顺手把它登记成传世神兵。', tier: 'elite', regionId: village, target: { kind: 'deliver', id: 'old-cleaver', label: '送修旧菜刀', contextTags: ['item:cleaver', 'npc:blacksmith'] }, reward: { wealth: 80, fame: 3, grantKey: 'commission:reward:cleaver-polish' } },
  { id: 'commission:night-watch', title: '客栈守夜', description: '在客栈守一晚，查清半夜响动究竟是贼、猫，还是老头的肚子。', tier: 'elite', regionId: village, target: { kind: 'investigate', id: 'inn-night-noise', label: '查明客栈夜间响动', contextTags: ['location:inn', 'event:night-watch'] }, reward: { wealth: 86, fame: 3, grantKey: 'commission:reward:night-watch' } },
  { id: 'commission:hill-scout', title: '山路探哨', description: '沿山路确认巡逻哨的位置，让下一支商队少走一次迷惑弯路。', tier: 'elite', regionId: village, target: { kind: 'investigate', id: 'hill-scout', label: '确认山路巡逻哨', contextTags: ['location:hill-path', 'event:scout'] }, reward: { wealth: 92, fame: 4, grantKey: 'commission:reward:hill-scout' } },
  { id: 'commission:recipe-clue', title: '刀谱寻味', description: '根据《百味刀谱》的一页残注，找出村里最像菜谱的武学线索。', tier: 'elite', regionId: village, target: { kind: 'investigate', id: 'recipe-clue', label: '查找刀谱残注线索', contextTags: ['item:hundred-flavors', 'quest:recipe-clue'] }, reward: { wealth: 100, fame: 5, grantKey: 'commission:reward:recipe-clue' } },
  { id: 'commission:first-cat-visit', title: '猫眼见证', description: '带大黄猫去鱼摊完成一次正式验货，商贩必须承认它看得比账房准。', tier: 'legendary', regionId: village, target: { kind: 'help', id: 'cat-fish-witness', label: '完成大黄猫鱼摊验货', contextTags: ['npc:dahuang-cat', 'location:fish-stall', 'quest:find-cat'] }, reward: { wealth: 160, fame: 8, grantKey: 'commission:reward:first-cat-visit' }, oneTime: true },
  { id: 'commission:village-oath', title: '小愚村公证', description: '替小愚村把一份菜刀盟约送到老头与大娘手里，双方都要当面盖章。', tier: 'legendary', regionId: village, target: { kind: 'deliver', id: 'village-oath', label: '完成小愚村菜刀盟约公证', contextTags: ['npc:old-man', 'npc:aunt', 'event:oath'] }, reward: { wealth: 180, fame: 10, grantKey: 'commission:reward:village-oath' }, oneTime: true },
  { id: 'commission:bai-rematch', title: '白大侠再约', description: '完成一次白大侠再约的正式切磋，赢了要记得先让他把台词说完。', tier: 'legendary', regionId: village, target: { kind: 'defeat', id: 'bai-rematch', label: '完成白大侠再约切磋', enemyId: 'bai-daxia', contextTags: ['npc:bai-daxia', 'battle:rematch'] }, reward: { wealth: 200, fame: 12, grantKey: 'commission:reward:bai-rematch' }, oneTime: true },
]

export const CORE_COMMISSION_TEMPLATES = commissionTemplates
