import { asContentKey } from '../../types/ids'
import type { SituationComboDefinition } from '../../types/comedy'

/** 门派情境组合只提交 Effect 请求，实际状态仍由 SituationComboEngine/EffectExecutor 结算。 */
export const sectSituationComboDefinitions: readonly SituationComboDefinition[] = [
  {
    id: 'situation:sect:shy-intel-report',
    layer: 'situation',
    scale: 'minor',
    triggerEvent: 'sect.dispatch_completed',
    conditions: [],
    requiredTags: ['sect', 'trait:shy', 'specialty:intel'],
    cooldownGroup: 'situation:sect:shy-intel-report',
    cooldownTicks: 1,
    firstCueId: 'cue:sect:shy-intel:first',
    repeatCueId: 'cue:sect:shy-intel:repeat',
    reducedMotionCueId: 'cue:sect:shy-intel:static',
    maxBlockingMs: 260,
    firstDiscoveryGrantKey: 'grant:situation:sect:shy-intel-report',
    effects: [{ type: 'change_stat', stat: 'fame', delta: 1 }, { type: 'narrate', lineId: asContentKey('line:sect:shy-intel-report') }],
  },
  {
    id: 'situation:sect:showoff-management',
    layer: 'situation',
    scale: 'minor',
    triggerEvent: 'sect.dispatch_completed',
    conditions: [],
    requiredTags: ['sect', 'trait:showoff', 'specialty:management'],
    cooldownGroup: 'situation:sect:showoff-management',
    cooldownTicks: 1,
    firstCueId: 'cue:sect:showoff-management:first',
    repeatCueId: 'cue:sect:showoff-management:repeat',
    reducedMotionCueId: 'cue:sect:showoff-management:static',
    maxBlockingMs: 260,
    firstDiscoveryGrantKey: 'grant:situation:sect:showoff-management',
    effects: [{ type: 'change_stat', stat: 'wealth', delta: 2 }, { type: 'narrate', lineId: asContentKey('line:sect:showoff-management') }],
  },
  {
    id: 'situation:sect:forge-kitchen',
    layer: 'situation',
    scale: 'minor',
    triggerEvent: 'sect.dispatch_completed',
    conditions: [],
    requiredTags: ['sect', 'specialty:forge', 'specialty:kitchen'],
    cooldownGroup: 'situation:sect:forge-kitchen',
    cooldownTicks: 1,
    firstCueId: 'cue:sect:forge-kitchen:first',
    repeatCueId: 'cue:sect:forge-kitchen:repeat',
    reducedMotionCueId: 'cue:sect:forge-kitchen:static',
    maxBlockingMs: 300,
    firstDiscoveryGrantKey: 'grant:situation:sect:forge-kitchen',
    effects: [{ type: 'change_stat', stat: 'sectProsperity', delta: 1 }, { type: 'narrate', lineId: asContentKey('line:sect:forge-kitchen') }],
  },
  {
    id: 'situation:sect:steady-ledger',
    layer: 'situation',
    scale: 'minor',
    triggerEvent: 'sect.dispatch_completed',
    conditions: [],
    requiredTags: ['sect', 'trait:steady', 'specialty:management'],
    cooldownGroup: 'situation:sect:steady-ledger',
    cooldownTicks: 1,
    firstCueId: 'cue:sect:steady-ledger:first',
    repeatCueId: 'cue:sect:steady-ledger:repeat',
    reducedMotionCueId: 'cue:sect:steady-ledger:static',
    maxBlockingMs: 240,
    firstDiscoveryGrantKey: 'grant:situation:sect:steady-ledger',
    effects: [{ type: 'change_stat', stat: 'wealth', delta: 1 }, { type: 'narrate', lineId: asContentKey('line:sect:steady-ledger') }],
  },
]

export const CORE_SECT_SITUATION_COMBOS = sectSituationComboDefinitions
