import { asAssetId, asWorldRegionId } from '../../types/ids'
import type { AssetDefinition, AssetManifest } from '../../types/assets'

export const CORE_ASSET_IDS = {
  menuBackground: asAssetId('asset:image:menu-valley'),
  villageBackground: asAssetId('asset:image:xiaoyu-village'),
  qingheMarketBackground: asAssetId('asset:image:qinghe-market'),
  hero: asAssetId('asset:image:hero'),
  elder: asAssetId('asset:image:elder'),
  cat: asAssetId('asset:image:cat'),
  bai: asAssetId('asset:image:bai'),
  aunt: asAssetId('asset:image:aunt'),
  qingheRegistrar: asAssetId('asset:image:qinghe-registrar'),
  qingheBoatwoman: asAssetId('asset:image:qinghe-boatwoman'),
  qingheTeaKeeper: asAssetId('asset:image:qinghe-tea-keeper'),
  qingheBangsi: asAssetId('asset:image:qinghe-bangsi'),
  blackwindFortressBackground: asAssetId('asset:image:blackwind-fortress'),
  blackwindLedgerKeeper: asAssetId('asset:image:blackwind-ledger-keeper'),
  blackwindRunner: asAssetId('asset:image:blackwind-runner'),
  blackwindCook: asAssetId('asset:image:blackwind-cook'),
  blackwindScout: asAssetId('asset:image:blackwind-scout'),
  blackwindLeader: asAssetId('asset:image:blackwind-leader'),
  qingyunMountainBackground: asAssetId('asset:image:qingyun-mountain'),
  qingyunDisciple: asAssetId('asset:image:qingyun-disciple'),
  qingyunHerbalist: asAssetId('asset:image:qingyun-herbalist'),
  qingyunBellKeeper: asAssetId('asset:image:qingyun-bell-keeper'),
  qingyunSwordDisciple: asAssetId('asset:image:qingyun-sword-disciple'),
  qingyunMaster: asAssetId('asset:image:qingyun-master'),
  westernRelayBackground: asAssetId('asset:image:western-relay'),
  westernCourier: asAssetId('asset:image:western-courier'),
  westernTeaKeeper: asAssetId('asset:image:western-tea-keeper'),
  westernGuard: asAssetId('asset:image:western-guard'),
  roadBandit: asAssetId('asset:image:road-bandit'),
  maskedBandit: asAssetId('asset:image:masked-bandit'),
  twinBandits: asAssetId('asset:image:twin-bandits'),
  donghaiTownBackground: asAssetId('asset:image:donghai-town'),
  donghaiBoatwoman: asAssetId('asset:image:donghai-boatwoman'),
  shellVendor: asAssetId('asset:image:shell-vendor'),
  tideBellKeeper: asAssetId('asset:image:tide-bell-keeper'),
  dockSmuggler: asAssetId('asset:image:dock-smuggler'),
  hookBandit: asAssetId('asset:image:hook-bandit'),
  tideMaster: asAssetId('asset:image:tide-master'),
  capitalRankingBackground: asAssetId('asset:image:capital-ranking'),
  capitalClerk: asAssetId('asset:image:capital-clerk'),
  capitalRegistrar: asAssetId('asset:image:capital-registrar'),
  capitalStoryteller: asAssetId('asset:image:capital-storyteller'),
  capitalArchivist: asAssetId('asset:image:capital-archivist'),
  capitalEnforcer: asAssetId('asset:image:capital-enforcer'),
  capitalScrollThief: asAssetId('asset:image:capital-scroll-thief'),
  rankingGovernor: asAssetId('asset:image:ranking-governor'),
  martialConventionBackground: asAssetId('asset:image:martial-convention'),
  conventionUsher: asAssetId('asset:image:convention-usher'),
  sectRepresentative: asAssetId('asset:image:sect-representative'),
  noodleVendor: asAssetId('asset:image:noodle-vendor'),
  conventionJudge: asAssetId('asset:image:convention-judge'),
  rivalMartialist: asAssetId('asset:image:rival-martialist'),
  conventionChallenger: asAssetId('asset:image:convention-challenger'),
  rankingMaster: asAssetId('asset:image:ranking-master'),
} as const

export const CORE_ASSETS: readonly AssetDefinition[] = [
  {
    id: CORE_ASSET_IDS.menuBackground,
    kind: 'image',
    format: 'webp',
    src: new URL('../../assets/backgrounds/menu-valley.webp', import.meta.url).href,
    usage: 'menu-background',
    sizeBytes: 289702,
    budgetBytes: 350000,
  },
  {
    id: CORE_ASSET_IDS.villageBackground,
    kind: 'image',
    format: 'webp',
    src: new URL('../../assets/backgrounds/xiaoyu-village.webp', import.meta.url).href,
    usage: 'region-background',
    sizeBytes: 313296,
    budgetBytes: 400000,
  },
  {
    id: CORE_ASSET_IDS.qingheMarketBackground,
    kind: 'image',
    format: 'webp',
    src: new URL('../../assets/backgrounds/qinghe-market.webp', import.meta.url).href,
    usage: 'region-background',
    sizeBytes: 307488,
    budgetBytes: 360000,
  },
  {
    id: CORE_ASSET_IDS.hero,
    kind: 'image',
    format: 'webp',
    src: new URL('../../assets/characters/hero.webp', import.meta.url).href,
    usage: 'character-sprite',
    sizeBytes: 93590,
    budgetBytes: 120000,
  },
  {
    id: CORE_ASSET_IDS.elder,
    kind: 'image',
    format: 'webp',
    src: new URL('../../assets/characters/elder.webp', import.meta.url).href,
    usage: 'character-sprite',
    sizeBytes: 102572,
    budgetBytes: 130000,
  },
  {
    id: CORE_ASSET_IDS.cat,
    kind: 'image',
    format: 'webp',
    src: new URL('../../assets/characters/cat.webp', import.meta.url).href,
    usage: 'character-sprite',
    sizeBytes: 134964,
    budgetBytes: 160000,
  },
  {
    id: CORE_ASSET_IDS.bai,
    kind: 'image',
    format: 'webp',
    src: new URL('../../assets/characters/bai.webp', import.meta.url).href,
    usage: 'character-sprite',
    sizeBytes: 96776,
    budgetBytes: 120000,
  },
  {
    id: CORE_ASSET_IDS.aunt,
    kind: 'image',
    format: 'webp',
    src: new URL('../../assets/characters/aunt.webp', import.meta.url).href,
    usage: 'character-sprite',
    sizeBytes: 105412,
    budgetBytes: 140000,
  },
  {
    id: CORE_ASSET_IDS.qingheRegistrar,
    kind: 'image',
    format: 'webp',
    src: new URL('../../assets/characters/qinghe-registrar.webp', import.meta.url).href,
    usage: 'character-sprite',
    sizeBytes: 116184,
    budgetBytes: 150000,
  },
  {
    id: CORE_ASSET_IDS.qingheBoatwoman,
    kind: 'image',
    format: 'webp',
    src: new URL('../../assets/characters/qinghe-boatwoman.webp', import.meta.url).href,
    usage: 'character-sprite',
    sizeBytes: 108550,
    budgetBytes: 150000,
  },
  {
    id: CORE_ASSET_IDS.qingheTeaKeeper,
    kind: 'image',
    format: 'webp',
    src: new URL('../../assets/characters/qinghe-tea-keeper.webp', import.meta.url).href,
    usage: 'character-sprite',
    sizeBytes: 107964,
    budgetBytes: 150000,
  },
  {
    id: CORE_ASSET_IDS.qingheBangsi,
    kind: 'image',
    format: 'webp',
    src: new URL('../../assets/characters/qinghe-bangsi.webp', import.meta.url).href,
    usage: 'character-sprite',
    sizeBytes: 60972,
    budgetBytes: 90000,
  },
  {
    id: CORE_ASSET_IDS.blackwindFortressBackground,
    kind: 'image',
    format: 'webp',
    src: new URL('../../assets/backgrounds/blackwind-fortress.webp', import.meta.url).href,
    usage: 'region-background',
    sizeBytes: 250078,
    budgetBytes: 320000,
  },
  {
    id: CORE_ASSET_IDS.blackwindLedgerKeeper,
    kind: 'image',
    format: 'webp',
    src: new URL('../../assets/characters/blackwind-ledger-keeper.webp', import.meta.url).href,
    usage: 'character-sprite',
    sizeBytes: 16782,
    budgetBytes: 50000,
  },
  {
    id: CORE_ASSET_IDS.blackwindRunner,
    kind: 'image',
    format: 'webp',
    src: new URL('../../assets/characters/blackwind-runner.webp', import.meta.url).href,
    usage: 'character-sprite',
    sizeBytes: 19744,
    budgetBytes: 50000,
  },
  {
    id: CORE_ASSET_IDS.blackwindCook,
    kind: 'image',
    format: 'webp',
    src: new URL('../../assets/characters/blackwind-cook.webp', import.meta.url).href,
    usage: 'character-sprite',
    sizeBytes: 18644,
    budgetBytes: 50000,
  },
  {
    id: CORE_ASSET_IDS.blackwindScout,
    kind: 'image',
    format: 'webp',
    src: new URL('../../assets/characters/blackwind-scout.webp', import.meta.url).href,
    usage: 'character-sprite',
    sizeBytes: 19284,
    budgetBytes: 50000,
  },
  {
    id: CORE_ASSET_IDS.blackwindLeader,
    kind: 'image',
    format: 'webp',
    src: new URL('../../assets/characters/blackwind-leader.webp', import.meta.url).href,
    usage: 'character-sprite',
    sizeBytes: 34674,
    budgetBytes: 70000,
  },
  {
    id: CORE_ASSET_IDS.qingyunMountainBackground,
    kind: 'image',
    format: 'webp',
    src: new URL('../../assets/backgrounds/qingyun-mountain.webp', import.meta.url).href,
    usage: 'region-background',
    sizeBytes: 287232,
    budgetBytes: 360000,
  },
  {
    id: CORE_ASSET_IDS.qingyunDisciple,
    kind: 'image',
    format: 'webp',
    src: new URL('../../assets/characters/qingyun-disciple.webp', import.meta.url).href,
    usage: 'character-sprite',
    sizeBytes: 31772,
    budgetBytes: 60000,
  },
  {
    id: CORE_ASSET_IDS.qingyunHerbalist,
    kind: 'image',
    format: 'webp',
    src: new URL('../../assets/characters/qingyun-herbalist.webp', import.meta.url).href,
    usage: 'character-sprite',
    sizeBytes: 56430,
    budgetBytes: 80000,
  },
  {
    id: CORE_ASSET_IDS.qingyunBellKeeper,
    kind: 'image',
    format: 'webp',
    src: new URL('../../assets/characters/qingyun-bell-keeper.webp', import.meta.url).href,
    usage: 'character-sprite',
    sizeBytes: 25386,
    budgetBytes: 60000,
  },
  {
    id: CORE_ASSET_IDS.qingyunSwordDisciple,
    kind: 'image',
    format: 'webp',
    src: new URL('../../assets/characters/qingyun-sword-disciple.webp', import.meta.url).href,
    usage: 'character-sprite',
    sizeBytes: 23454,
    budgetBytes: 60000,
  },
  {
    id: CORE_ASSET_IDS.qingyunMaster,
    kind: 'image',
    format: 'webp',
    src: new URL('../../assets/characters/qingyun-master.webp', import.meta.url).href,
    usage: 'character-sprite',
    sizeBytes: 38170,
    budgetBytes: 80000,
  },
  { id: CORE_ASSET_IDS.westernRelayBackground, kind: 'image', format: 'webp', src: new URL('../../assets/backgrounds/western-relay.webp', import.meta.url).href, usage: 'region-background', sizeBytes: 141610, budgetBytes: 220000 },
  { id: CORE_ASSET_IDS.westernCourier, kind: 'image', format: 'webp', src: new URL('../../assets/characters/western-courier.webp', import.meta.url).href, usage: 'character-sprite', sizeBytes: 25098, budgetBytes: 60000 },
  { id: CORE_ASSET_IDS.westernTeaKeeper, kind: 'image', format: 'webp', src: new URL('../../assets/characters/western-tea-keeper.webp', import.meta.url).href, usage: 'character-sprite', sizeBytes: 32152, budgetBytes: 70000 },
  { id: CORE_ASSET_IDS.westernGuard, kind: 'image', format: 'webp', src: new URL('../../assets/characters/western-guard.webp', import.meta.url).href, usage: 'character-sprite', sizeBytes: 29050, budgetBytes: 60000 },
  { id: CORE_ASSET_IDS.roadBandit, kind: 'image', format: 'webp', src: new URL('../../assets/characters/road-bandit.webp', import.meta.url).href, usage: 'character-sprite', sizeBytes: 39012, budgetBytes: 80000 },
  { id: CORE_ASSET_IDS.maskedBandit, kind: 'image', format: 'webp', src: new URL('../../assets/characters/masked-bandit.webp', import.meta.url).href, usage: 'character-sprite', sizeBytes: 28192, budgetBytes: 70000 },
  { id: CORE_ASSET_IDS.twinBandits, kind: 'image', format: 'webp', src: new URL('../../assets/characters/twin-bandits.webp', import.meta.url).href, usage: 'character-sprite', sizeBytes: 42704, budgetBytes: 90000 },
  { id: CORE_ASSET_IDS.donghaiTownBackground, kind: 'image', format: 'webp', src: new URL('../../assets/backgrounds/donghai-town.webp', import.meta.url).href, usage: 'region-background', sizeBytes: 193590, budgetBytes: 280000 },
  { id: CORE_ASSET_IDS.donghaiBoatwoman, kind: 'image', format: 'webp', src: new URL('../../assets/characters/donghai-boatwoman.webp', import.meta.url).href, usage: 'character-sprite', sizeBytes: 32194, budgetBytes: 70000 },
  { id: CORE_ASSET_IDS.shellVendor, kind: 'image', format: 'webp', src: new URL('../../assets/characters/shell-vendor.webp', import.meta.url).href, usage: 'character-sprite', sizeBytes: 38508, budgetBytes: 80000 },
  { id: CORE_ASSET_IDS.tideBellKeeper, kind: 'image', format: 'webp', src: new URL('../../assets/characters/tide-bell-keeper.webp', import.meta.url).href, usage: 'character-sprite', sizeBytes: 38338, budgetBytes: 80000 },
  { id: CORE_ASSET_IDS.dockSmuggler, kind: 'image', format: 'webp', src: new URL('../../assets/characters/dock-smuggler.webp', import.meta.url).href, usage: 'character-sprite', sizeBytes: 28844, budgetBytes: 70000 },
  { id: CORE_ASSET_IDS.hookBandit, kind: 'image', format: 'webp', src: new URL('../../assets/characters/hook-bandit.webp', import.meta.url).href, usage: 'character-sprite', sizeBytes: 36166, budgetBytes: 80000 },
  { id: CORE_ASSET_IDS.tideMaster, kind: 'image', format: 'webp', src: new URL('../../assets/characters/tide-master.webp', import.meta.url).href, usage: 'character-sprite', sizeBytes: 46846, budgetBytes: 100000 },
  { id: CORE_ASSET_IDS.capitalRankingBackground, kind: 'image', format: 'webp', src: new URL('../../assets/backgrounds/capital-ranking.webp', import.meta.url).href, usage: 'region-background', sizeBytes: 192670, budgetBytes: 280000 },
  { id: CORE_ASSET_IDS.capitalClerk, kind: 'image', format: 'webp', src: new URL('../../assets/characters/capital-clerk.webp', import.meta.url).href, usage: 'character-sprite', sizeBytes: 17886, budgetBytes: 50000 },
  { id: CORE_ASSET_IDS.capitalRegistrar, kind: 'image', format: 'webp', src: new URL('../../assets/characters/capital-registrar.webp', import.meta.url).href, usage: 'character-sprite', sizeBytes: 22780, budgetBytes: 60000 },
  { id: CORE_ASSET_IDS.capitalStoryteller, kind: 'image', format: 'webp', src: new URL('../../assets/characters/capital-storyteller.webp', import.meta.url).href, usage: 'character-sprite', sizeBytes: 25870, budgetBytes: 70000 },
  { id: CORE_ASSET_IDS.capitalArchivist, kind: 'image', format: 'webp', src: new URL('../../assets/characters/capital-archivist.webp', import.meta.url).href, usage: 'character-sprite', sizeBytes: 19254, budgetBytes: 50000 },
  { id: CORE_ASSET_IDS.capitalEnforcer, kind: 'image', format: 'webp', src: new URL('../../assets/characters/capital-enforcer.webp', import.meta.url).href, usage: 'character-sprite', sizeBytes: 27434, budgetBytes: 70000 },
  { id: CORE_ASSET_IDS.capitalScrollThief, kind: 'image', format: 'webp', src: new URL('../../assets/characters/capital-scroll-thief.webp', import.meta.url).href, usage: 'character-sprite', sizeBytes: 27558, budgetBytes: 70000 },
  { id: CORE_ASSET_IDS.rankingGovernor, kind: 'image', format: 'webp', src: new URL('../../assets/characters/ranking-governor.webp', import.meta.url).href, usage: 'character-sprite', sizeBytes: 37502, budgetBytes: 90000 },
  { id: CORE_ASSET_IDS.martialConventionBackground, kind: 'image', format: 'webp', src: new URL('../../assets/backgrounds/martial-convention.webp', import.meta.url).href, usage: 'region-background', sizeBytes: 169758, budgetBytes: 260000 },
  { id: CORE_ASSET_IDS.conventionUsher, kind: 'image', format: 'webp', src: new URL('../../assets/characters/convention-usher.webp', import.meta.url).href, usage: 'character-sprite', sizeBytes: 23346, budgetBytes: 60000 },
  { id: CORE_ASSET_IDS.sectRepresentative, kind: 'image', format: 'webp', src: new URL('../../assets/characters/sect-representative.webp', import.meta.url).href, usage: 'character-sprite', sizeBytes: 24816, budgetBytes: 60000 },
  { id: CORE_ASSET_IDS.noodleVendor, kind: 'image', format: 'webp', src: new URL('../../assets/characters/noodle-vendor.webp', import.meta.url).href, usage: 'character-sprite', sizeBytes: 28394, budgetBytes: 70000 },
  { id: CORE_ASSET_IDS.conventionJudge, kind: 'image', format: 'webp', src: new URL('../../assets/characters/convention-judge.webp', import.meta.url).href, usage: 'character-sprite', sizeBytes: 33838, budgetBytes: 80000 },
  { id: CORE_ASSET_IDS.rivalMartialist, kind: 'image', format: 'webp', src: new URL('../../assets/characters/rival-martialist.webp', import.meta.url).href, usage: 'character-sprite', sizeBytes: 32456, budgetBytes: 80000 },
  { id: CORE_ASSET_IDS.conventionChallenger, kind: 'image', format: 'webp', src: new URL('../../assets/characters/convention-challenger.webp', import.meta.url).href, usage: 'character-sprite', sizeBytes: 37046, budgetBytes: 90000 },
  { id: CORE_ASSET_IDS.rankingMaster, kind: 'image', format: 'webp', src: new URL('../../assets/characters/ranking-master.webp', import.meta.url).href, usage: 'character-sprite', sizeBytes: 46822, budgetBytes: 100000 },
]

const villageRegionId = asWorldRegionId('xiaoyu-village')
const qingheRegionId = asWorldRegionId('qinghe-county')
const blackwindRegionId = asWorldRegionId('blackwind-fortress')
const qingyunRegionId = asWorldRegionId('qingyun-mountain')
const westernRelayRegionId = asWorldRegionId('western-relay')
const donghaiRegionId = asWorldRegionId('donghai-town')
const capitalRankingRegionId = asWorldRegionId('capital-ranking')
const martialConventionRegionId = asWorldRegionId('martial-convention')

export const CORE_ASSET_MANIFEST: AssetManifest = {
  version: 1,
  assets: CORE_ASSETS,
  globalAssetIds: [CORE_ASSET_IDS.menuBackground, CORE_ASSET_IDS.hero, CORE_ASSET_IDS.elder, CORE_ASSET_IDS.cat],
  regions: [
    {
      regionId: villageRegionId,
      assetIds: [CORE_ASSET_IDS.villageBackground, CORE_ASSET_IDS.hero, CORE_ASSET_IDS.elder, CORE_ASSET_IDS.cat, CORE_ASSET_IDS.bai, CORE_ASSET_IDS.aunt],
      budgetBytes: 900000,
    },
    {
      regionId: qingheRegionId,
      assetIds: [
        CORE_ASSET_IDS.qingheMarketBackground,
        CORE_ASSET_IDS.qingheRegistrar,
        CORE_ASSET_IDS.qingheBoatwoman,
        CORE_ASSET_IDS.qingheTeaKeeper,
        CORE_ASSET_IDS.qingheBangsi,
      ],
      budgetBytes: 1000000,
    },
    {
      regionId: blackwindRegionId,
      assetIds: [
        CORE_ASSET_IDS.blackwindFortressBackground,
        CORE_ASSET_IDS.blackwindLedgerKeeper,
        CORE_ASSET_IDS.blackwindRunner,
        CORE_ASSET_IDS.blackwindCook,
        CORE_ASSET_IDS.blackwindScout,
        CORE_ASSET_IDS.blackwindLeader,
      ],
      budgetBytes: 800000,
    },
    {
      regionId: qingyunRegionId,
      assetIds: [
        CORE_ASSET_IDS.qingyunMountainBackground,
        CORE_ASSET_IDS.qingyunDisciple,
        CORE_ASSET_IDS.qingyunHerbalist,
        CORE_ASSET_IDS.qingyunBellKeeper,
        CORE_ASSET_IDS.qingyunSwordDisciple,
        CORE_ASSET_IDS.qingyunMaster,
      ],
      budgetBytes: 800000,
    },
    { regionId: westernRelayRegionId, assetIds: [CORE_ASSET_IDS.westernRelayBackground, CORE_ASSET_IDS.westernCourier, CORE_ASSET_IDS.westernTeaKeeper, CORE_ASSET_IDS.westernGuard, CORE_ASSET_IDS.roadBandit, CORE_ASSET_IDS.maskedBandit, CORE_ASSET_IDS.twinBandits], budgetBytes: 800000 },
    { regionId: donghaiRegionId, assetIds: [CORE_ASSET_IDS.donghaiTownBackground, CORE_ASSET_IDS.donghaiBoatwoman, CORE_ASSET_IDS.shellVendor, CORE_ASSET_IDS.tideBellKeeper, CORE_ASSET_IDS.dockSmuggler, CORE_ASSET_IDS.hookBandit, CORE_ASSET_IDS.tideMaster], budgetBytes: 900000 },
    { regionId: capitalRankingRegionId, assetIds: [CORE_ASSET_IDS.capitalRankingBackground, CORE_ASSET_IDS.capitalClerk, CORE_ASSET_IDS.capitalRegistrar, CORE_ASSET_IDS.capitalStoryteller, CORE_ASSET_IDS.capitalArchivist, CORE_ASSET_IDS.capitalEnforcer, CORE_ASSET_IDS.capitalScrollThief, CORE_ASSET_IDS.rankingGovernor], budgetBytes: 900000 },
    { regionId: martialConventionRegionId, assetIds: [CORE_ASSET_IDS.martialConventionBackground, CORE_ASSET_IDS.conventionUsher, CORE_ASSET_IDS.sectRepresentative, CORE_ASSET_IDS.noodleVendor, CORE_ASSET_IDS.conventionJudge, CORE_ASSET_IDS.rivalMartialist, CORE_ASSET_IDS.conventionChallenger, CORE_ASSET_IDS.rankingMaster], budgetBytes: 900000 },
  ],
}

export const coreAssetManifest = CORE_ASSET_MANIFEST
