import { asDialogueId, asDiscipleId } from '../../types/ids'
import type { DiscipleDefinition, DiscipleDispatchEventDefinition, DiscipleTraitDefinition } from '../../types/disciple'

export const discipleTraitDefinitions: readonly DiscipleTraitDefinition[] = [
  { id: 'shy', name: '社恐', description: '少说废话，多做准备，派遣质量略有提升但会多花一点时间。', modifiers: { durationTicksDelta: 1, qualityDelta: 1 } },
  { id: 'showoff', name: '显眼包', description: '动静很大，收尾更快，但成功率修正极小。', modifiers: { durationTicksDelta: -1, successChanceDelta: -0.03 } },
  { id: 'steady', name: '稳如老狗', description: '不追求戏剧效果，稳稳给出一点成功率。', modifiers: { successChanceDelta: 0.05 } },
  { id: 'craftsman', name: '手痒匠心', description: '看见缺口就想补，派遣质量略有提升但会多花一点时间。', modifiers: { durationTicksDelta: 1, qualityDelta: 1 } },
  { id: 'cook', name: '闻香识味', description: '先闻一遍再下锅，派遣成功率得到轻微提升。', modifiers: { successChanceDelta: 0.04 } },
  { id: 'listener', name: '耳朵尖', description: '连风吹过瓦片的口音都记得，派遣收尾略快。', modifiers: { durationTicksDelta: -1, successChanceDelta: 0.03 } },
  { id: 'manager', name: '清醒账房', description: '每笔开支都有去处，派遣质量得到轻微提升。', modifiers: { qualityDelta: 1 } },
]

export const discipleDefinitions: readonly DiscipleDefinition[] = [
  {
    id: asDiscipleId('disciple:shy-scholar'),
    name: '沈算盘',
    description: '说话前先打草稿，派遣前会把路线算三遍。',
    recruitment: { requiredChapter: 5 },
    traitIds: ['shy', 'steady'],
    specialty: 'management',
    dispatchEventIds: ['dispatch-event:shy-scholar:ledger-check'],
    recruitmentDialogueId: asDialogueId('dialogue:disciple:shy:recruit'),
    dialogueIds: [asDialogueId('dialogue:disciple:shy:short')],
  },
  {
    id: asDiscipleId('disciple:showoff-runner'),
    name: '陆显眼',
    description: '每次出门都要让全江湖知道自己出门了。',
    recruitment: { requiredChapter: 5, conditions: [{ type: 'flag_equals', flag: 'met_showoff_runner', value: true }] },
    traitIds: ['showoff'],
    specialty: 'intel',
    dispatchEventIds: ['dispatch-event:showoff-runner:rumor-broadcast'],
    recruitmentDialogueId: asDialogueId('dialogue:disciple:showoff:recruit'),
    dialogueIds: [asDialogueId('dialogue:disciple:showoff:short')],
  },
  {
    id: asDiscipleId('disciple:forge-aunt'),
    name: '唐铁衣',
    description: '见到坏掉的兵器会先叹气，再把它修到比原来更有脾气。',
    recruitment: { requiredChapter: 5, conditions: [{ type: 'flag_equals', flag: 'met_forge_keeper', value: true }] },
    traitIds: ['craftsman', 'steady'],
    specialty: 'forge',
    dispatchEventIds: ['dispatch-event:forge-aunt:borrowed-hammer'],
    recruitmentDialogueId: asDialogueId('dialogue:disciple:forge:recruit'),
    dialogueIds: [asDialogueId('dialogue:disciple:forge:short')],
  },
  {
    id: asDiscipleId('disciple:kitchen-apprentice'),
    name: '灶边小满',
    description: '能把一锅糊粥讲成火候试验，偏偏成品真的能让人吃饱。',
    recruitment: { requiredChapter: 5, conditions: [{ type: 'flag_equals', flag: 'met_kitchen_helper', value: true }] },
    traitIds: ['cook', 'shy'],
    specialty: 'kitchen',
    dispatchEventIds: ['dispatch-event:kitchen-apprentice:travel-rations'],
    recruitmentDialogueId: asDialogueId('dialogue:disciple:kitchen:recruit'),
    dialogueIds: [asDialogueId('dialogue:disciple:kitchen:short')],
  },
  {
    id: asDiscipleId('disciple:quiet-listener'),
    name: '叶听风',
    description: '不爱抢话，却能从三句闲聊里听出一条完整的江湖路线。',
    recruitment: { requiredChapter: 5, conditions: [{ type: 'flag_equals', flag: 'heard_rumor_network', value: true }] },
    traitIds: ['listener', 'steady'],
    specialty: 'intel',
    dispatchEventIds: ['dispatch-event:quiet-listener:three-clues'],
    recruitmentDialogueId: asDialogueId('dialogue:disciple:listener:recruit'),
    dialogueIds: [asDialogueId('dialogue:disciple:listener:short')],
  },
  {
    id: asDiscipleId('disciple:ledger-keeper'),
    name: '顾全账',
    description: '把门派账本当武学秘籍背，连扫帚折了都能算出合理解释。',
    recruitment: { requiredChapter: 5, conditions: [{ type: 'flag_equals', flag: 'settled_sect_ledger', value: true }] },
    traitIds: ['manager', 'steady'],
    specialty: 'management',
    dispatchEventIds: ['dispatch-event:ledger-keeper:three-columns'],
    recruitmentDialogueId: asDialogueId('dialogue:disciple:manager:recruit'),
    dialogueIds: [asDialogueId('dialogue:disciple:manager:short')],
  },
]

export const discipleDispatchEventDefinitions: readonly DiscipleDispatchEventDefinition[] = [
  {
    id: 'dispatch-event:shy-scholar:ledger-check',
    discipleId: asDiscipleId('disciple:shy-scholar'),
    title: '算盘先把账对上',
    description: '沈算盘不肯当面汇报，先把路线、损耗和回程时辰写成三栏小账。',
    triggerEvent: 'sect.dispatch_completed',
    specialty: 'management',
    requiredTraitIds: ['shy'],
    feedback: '路线被整理成可复用的门派经营记录。',
    effect: { type: 'change_stat', stat: 'sectProsperity', delta: 1 },
  },
  {
    id: 'dispatch-event:showoff-runner:rumor-broadcast',
    discipleId: asDiscipleId('disciple:showoff-runner'),
    title: '显眼包的风声扩音',
    description: '陆显眼把一条普通口信说成江湖头条，倒也让更多人记住了门派名号。',
    triggerEvent: 'sect.dispatch_completed',
    specialty: 'intel',
    requiredTraitIds: ['showoff'],
    feedback: '门派名号被顺手传开，获得少量名望。',
    effect: { type: 'change_stat', stat: 'fame', delta: 1 },
  },
  {
    id: 'dispatch-event:forge-aunt:borrowed-hammer',
    discipleId: asDiscipleId('disciple:forge-aunt'),
    title: '借来的锤子也要登记',
    description: '唐铁衣修好委托物后，顺手把借来的锤子擦亮并归还，铁匠铺少了一笔糊涂账。',
    triggerEvent: 'sect.dispatch_completed',
    specialty: 'forge',
    requiredTraitIds: ['craftsman'],
    feedback: '铁匠铺的规整度提升，门派繁荣小幅增加。',
    effect: { type: 'change_stat', stat: 'sectProsperity', delta: 1 },
  },
  {
    id: 'dispatch-event:kitchen-apprentice:travel-rations',
    discipleId: asDiscipleId('disciple:kitchen-apprentice'),
    title: '路粮没有第三种熟度',
    description: '灶边小满把干粮分成恰好够用的份量，派遣队伍不用再拿路边野果赌运气。',
    triggerEvent: 'sect.dispatch_completed',
    specialty: 'kitchen',
    requiredTraitIds: ['cook'],
    feedback: '厨房的路粮周转更稳，经营账面回收少量财富。',
    effect: { type: 'change_stat', stat: 'wealth', delta: 1 },
  },
  {
    id: 'dispatch-event:quiet-listener:three-clues',
    discipleId: asDiscipleId('disciple:quiet-listener'),
    title: '三句闲聊拼成一张图',
    description: '叶听风把茶摊、渡口和驿站的三句闲话拼成一条可行动的线索。',
    triggerEvent: 'sect.dispatch_completed',
    specialty: 'intel',
    requiredTraitIds: ['listener'],
    feedback: '情报堂补全一条区域线索，获得少量名望。',
    effect: { type: 'change_stat', stat: 'fame', delta: 1 },
  },
  {
    id: 'dispatch-event:ledger-keeper:three-columns',
    discipleId: asDiscipleId('disciple:ledger-keeper'),
    title: '三栏账本不许串行',
    description: '顾全账把收入、消耗和下次预留分开登记，连门人都看得懂这次赚没赚。',
    triggerEvent: 'sect.dispatch_completed',
    specialty: 'management',
    requiredTraitIds: ['manager'],
    feedback: '经营收益被清楚归档，门派繁荣小幅增加。',
    effect: { type: 'change_stat', stat: 'sectProsperity', delta: 1 },
  },
]

export const CORE_DISCIPLE_DEFINITIONS = discipleDefinitions
export const CORE_DISCIPLE_TRAITS = discipleTraitDefinitions
export const CORE_DISCIPLE_DISPATCH_EVENTS = discipleDispatchEventDefinitions
