export {
  NPC_INTERACTION_EVENT,
  NpcEngine,
  NpcEngineError,
  NpcSnapshotError,
  NpcStateEngine,
  applyNpcInteraction,
  assertValidNpcDefinitions,
  createNpcEngine,
  createNpcInteractionEvent,
  getNpcPresence,
  parseNpcSnapshot,
  restoreNpcSnapshot,
  serializeNpcSnapshot,
  validateNpcDefinitions,
} from './engine'
export type {
  NpcAppearanceDefinition,
  NpcDefinition,
  NpcInteractionEffect,
  NpcInteractionEvent,
  NpcInteractionKind,
  NpcInteractionOutcome,
  NpcPresence,
  NpcPresenceContext,
  NpcQuestState,
  NpcRelationshipBounds,
  NpcRelationshipState,
  NpcSnapshot,
  NpcTaskAction,
  NpcTaskActionKind,
  NpcValidationIssue,
  NpcValidationResult,
} from '../../types/npc'
