import type { ChapterEnemyDefinition } from '../../types/chapter-combat'
import { asChapterId, asEnemyId } from '../../types/ids'

const chapterId = asChapterId('ch06')
const normal = (id: string, name: string, power: number, posture: number): ChapterEnemyDefinition => ({ id: asEnemyId(`enemy:ch06:${id}`), chapterId, role: 'normal', name, readableIntent: true, behavior: { id: `template:ch06:${id}`, name: `${name}的潮汐套路`, moveIds: [`move:ch06:${id}:strike`, `move:ch06:${id}:guard`, `move:ch06:${id}:splash`], fallbackMoveId: `move:ch06:${id}:strike`, tags: ['honest-intent', 'normal', 'tide'] }, moves: [{ id: `move:ch06:${id}:strike`, name: '潮头短打', kind: 'aggressive', summary: `预计造成稳定伤害，并削减 ${posture} 点架势。`, weight: 3, power, posturePower: posture }, { id: `move:ch06:${id}:guard`, name: '贝壳回身', kind: 'defend', summary: '用贝壳和水幕减伤约 30%。', weight: 1, guardRatio: .3 }, { id: `move:ch06:${id}:splash`, name: '盐花飞溅', kind: 'special', summary: '预计造成轻度伤害并扰乱下一次命中。', weight: 1, power: .72, posturePower: 4 }], curve: { maxHp: { base: id === 'dock-smuggler' ? 112 : 118 }, maxQi: { base: 24 }, attack: { base: 16 }, defense: { base: 7 }, posture: { base: 42 }, accuracy: { base: .88 }, dodge: { base: .08 }, crit: { base: .07 } } })
const bossBehavior = { id: 'template:ch06:tide-master', name: '潮涨潮落四段论', moveIds: ['move:ch06:tide:bell', 'move:ch06:tide:surge', 'move:ch06:tide:guard', 'move:ch06:tide:undertow'], fallbackMoveId: 'move:ch06:tide:bell', tags: ['honest-intent', 'boss', 'readable-phase', 'tide-cycle'] } as const
export const CH06_ENEMY_DEFINITIONS: readonly ChapterEnemyDefinition[] = [
  normal('dock-smuggler', '码头私运客', 1.05, 8), normal('hook-raider', '钩浪劫客', 1.1, 9),
  { id: asEnemyId('enemy:ch06:tide-master'), chapterId, role: 'boss', name: '海潮帮主', readableIntent: true, specialRuleIds: ['rule:ch06:tide:bell'], presentationCueIds: ['presentation:ch06:tide:defeat'], behavior: bossBehavior, moves: [{ id: 'move:ch06:tide:bell', name: '潮钟点名', kind: 'aggressive', summary: '预计造成约 26 点伤害，并削减 11 点架势。', weight: 3, power: 1.14, posturePower: 11 }, { id: 'move:ch06:tide:surge', name: '带货涨潮', kind: 'special', summary: '不造成伤害，下一回合潮势会增强。', weight: 1, power: 0, posturePower: 0 }, { id: 'move:ch06:tide:guard', name: '贝壳潮盾', kind: 'defend', summary: '借潮盾减伤约 30%。', weight: 1, guardRatio: .3 }, { id: 'move:ch06:tide:undertow', name: '回流压岸', kind: 'aggressive', summary: '预计造成约 34 点伤害，并削减 14 点架势。', weight: 3, power: 1.4, posturePower: 14 }], curve: { maxHp: { base: 204 }, maxQi: { base: 58 }, attack: { base: 23 }, defense: { base: 14 }, posture: { base: 54 }, accuracy: { base: .9 }, dodge: { base: .06 }, crit: { base: .1 } }, boss: { phases: [{ id: 'phase:ch06:tide:opening', phase: 1, hpThresholdRatio: 1, moveIds: ['move:ch06:tide:bell', 'move:ch06:tide:surge', 'move:ch06:tide:guard'] }, { id: 'phase:ch06:tide:undertow', phase: 2, hpThresholdRatio: .5, moveIds: ['move:ch06:tide:undertow', 'move:ch06:tide:surge', 'move:ch06:tide:guard'], deceptiveChance: .2 }] } },
]
export const ch06EnemyDefinitions = CH06_ENEMY_DEFINITIONS
