import type { ChapterEnemyDefinition } from '../../types/chapter-combat'
import { asChapterId, asEnemyId } from '../../types/ids'

const chapterId = asChapterId('ch07')
const normal = (id: string, name: string, power: number, posture: number): ChapterEnemyDefinition => ({ id: asEnemyId(`enemy:ch07:${id}`), chapterId, role: 'normal', name, readableIntent: true, behavior: { id: `template:ch07:${id}`, name: `${name}的榜单套路`, moveIds: [`move:ch07:${id}:strike`, `move:ch07:${id}:guard`, `move:ch07:${id}:ink`], fallbackMoveId: `move:ch07:${id}:strike`, tags: ['honest-intent', 'normal', 'ranking'] }, moves: [{ id: `move:ch07:${id}:strike`, name: '榜纸拍击', kind: 'aggressive', summary: `预计造成稳定伤害，并削减 ${posture} 点架势。`, weight: 3, power, posturePower: posture }, { id: `move:ch07:${id}:guard`, name: '卷宗遮面', kind: 'defend', summary: '用卷宗减伤约 30%。', weight: 1, guardRatio: .3 }, { id: `move:ch07:${id}:ink`, name: '墨迹误导', kind: 'special', summary: '预计造成轻度伤害，下一回合命中会变得不稳定。', weight: 1, power: .74, posturePower: 4 }], curve: { maxHp: { base: id === 'archive-guard' ? 120 : 126 }, maxQi: { base: 25 }, attack: { base: 17 }, defense: { base: 8 }, posture: { base: 44 }, accuracy: { base: .89 }, dodge: { base: .08 }, crit: { base: .08 } } })
const bossBehavior = { id: 'template:ch07:ranking-governor', name: '榜司三层审计', moveIds: ['move:ch07:governor:stamp', 'move:ch07:governor:blur', 'move:ch07:governor:guard', 'move:ch07:governor:publish'], fallbackMoveId: 'move:ch07:governor:stamp', tags: ['honest-intent', 'boss', 'readable-phase', 'audit'] } as const
export const CH07_ENEMY_DEFINITIONS: readonly ChapterEnemyDefinition[] = [
  normal('archive-guard', '档案守门人', 1.08, 8), normal('ranking-enforcer', '榜司执行客', 1.13, 9),
  { id: asEnemyId('enemy:ch07:ranking-governor'), chapterId, role: 'boss', name: '榜司督主', readableIntent: true, specialRuleIds: ['rule:ch07:governor:publish'], presentationCueIds: ['presentation:ch07:governor:defeat'], behavior: bossBehavior, moves: [{ id: 'move:ch07:governor:stamp', name: '印章定价', kind: 'aggressive', summary: '预计造成约 28 点伤害，并削减 12 点架势。', weight: 3, power: 1.16, posturePower: 12 }, { id: 'move:ch07:governor:blur', name: '榜文模糊', kind: 'special', summary: '本回合不攻击，下一次意图可能被改写。', weight: 1, power: 0, posturePower: 0 }, { id: 'move:ch07:governor:guard', name: '卷宗叠甲', kind: 'defend', summary: '用卷宗减伤约 30%。', weight: 1, guardRatio: .3 }, { id: 'move:ch07:governor:publish', name: '热榜发布', kind: 'aggressive', summary: '预计造成约 37 点伤害，并削减 15 点架势。', weight: 3, power: 1.42, posturePower: 15 }], curve: { maxHp: { base: 218 }, maxQi: { base: 62 }, attack: { base: 24 }, defense: { base: 15 }, posture: { base: 63 }, accuracy: { base: .91 }, dodge: { base: .06 }, crit: { base: .11 } }, boss: { phases: [{ id: 'phase:ch07:governor:opening', phase: 1, hpThresholdRatio: 1, moveIds: ['move:ch07:governor:stamp', 'move:ch07:governor:blur', 'move:ch07:governor:guard'] }, { id: 'phase:ch07:governor:publish', phase: 2, hpThresholdRatio: .5, moveIds: ['move:ch07:governor:publish', 'move:ch07:governor:blur', 'move:ch07:governor:guard'], deceptiveChance: .2 }] } },
]
export const ch07EnemyDefinitions = CH07_ENEMY_DEFINITIONS
