import type { ChapterEnemyDefinition } from '../../types/chapter-combat'
import { asChapterId, asEnemyId } from '../../types/ids'

const chapterId = asChapterId('ch08')
const normal = (id: string, name: string, power: number, posture: number): ChapterEnemyDefinition => ({ id: asEnemyId(`enemy:ch08:${id}`), chapterId, role: 'normal', name, readableIntent: true, behavior: { id: `template:ch08:${id}`, name: `${name}的会场套路`, moveIds: [`move:ch08:${id}:strike`, `move:ch08:${id}:guard`, `move:ch08:${id}:pepper`], fallbackMoveId: `move:ch08:${id}:strike`, tags: ['honest-intent', 'normal', 'convention'] }, moves: [{ id: `move:ch08:${id}:strike`, name: '会场短打', kind: 'aggressive', summary: `预计造成稳定伤害，并削减 ${posture} 点架势。`, weight: 3, power, posturePower: posture }, { id: `move:ch08:${id}:guard`, name: '评委牌遮身', kind: 'defend', summary: '用评委牌减伤约 30%。', weight: 1, guardRatio: .3 }, { id: `move:ch08:${id}:pepper`, name: '椒香扰场', kind: 'special', summary: '预计造成轻度伤害并扰乱下一次命中。', weight: 1, power: .75, posturePower: 4 }], curve: { maxHp: { base: id === 'rival-martialist' ? 130 : 136 }, maxQi: { base: 27 }, attack: { base: 18 }, defense: { base: 8 }, posture: { base: 46 }, accuracy: { base: .89 }, dodge: { base: .08 }, crit: { base: .08 } } })
const bossBehavior = { id: 'template:ch08:ranking-master', name: '定义权五段评审', moveIds: ['move:ch08:master:score', 'move:ch08:master:abstain', 'move:ch08:master:guard', 'move:ch08:master:verdict'], fallbackMoveId: 'move:ch08:master:score', tags: ['honest-intent', 'boss', 'readable-phase', 'final-definition'] } as const
export const CH08_ENEMY_DEFINITIONS: readonly ChapterEnemyDefinition[] = [
  normal('rival-martialist', '争榜武人', 1.1, 9), normal('convention-enforcer', '会场执事', 1.16, 10),
  { id: asEnemyId('enemy:ch08:ranking-master'), chapterId, role: 'boss', name: '百晓榜主', readableIntent: true, specialRuleIds: ['rule:ch08:master:verdict'], presentationCueIds: ['presentation:ch08:master:defeat'], behavior: bossBehavior, moves: [{ id: 'move:ch08:master:score', name: '评审落笔', kind: 'aggressive', summary: '预计造成约 30 点伤害，并削减 12 点架势。', weight: 3, power: 1.18, posturePower: 12 }, { id: 'move:ch08:master:abstain', name: '暂不定义', kind: 'special', summary: '本回合不攻击，观察你如何选择下一页。', weight: 1, power: 0, posturePower: 0 }, { id: 'move:ch08:master:guard', name: '榜册叠甲', kind: 'defend', summary: '用榜册减伤约 30%。', weight: 1, guardRatio: .3 }, { id: 'move:ch08:master:verdict', name: '终局判词', kind: 'aggressive', summary: '预计造成约 40 点伤害，并削减 16 点架势。', weight: 3, power: 1.45, posturePower: 16 }], curve: { maxHp: { base: 236 }, maxQi: { base: 66 }, attack: { base: 25 }, defense: { base: 16 }, posture: { base: 58 }, accuracy: { base: .91 }, dodge: { base: .06 }, crit: { base: .11 } }, boss: { phases: [{ id: 'phase:ch08:master:opening', phase: 1, hpThresholdRatio: 1, moveIds: ['move:ch08:master:score', 'move:ch08:master:abstain', 'move:ch08:master:guard'] }, { id: 'phase:ch08:master:verdict', phase: 2, hpThresholdRatio: .5, moveIds: ['move:ch08:master:verdict', 'move:ch08:master:abstain', 'move:ch08:master:guard'], deceptiveChance: .2 }] } },
]
export const ch08EnemyDefinitions = CH08_ENEMY_DEFINITIONS
